apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eooorbyrk-nodejs 
  janus-idp.io/tekton: eooorbyrk-nodejs
  backstage.io/kubernetes-id: eooorbyrk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eooorbyrk-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml